<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def mul(q,v): #CALLING FUNCTION
    for i in range(r1):  
        p_mat=[]
        for j in range(c2):
            temp=0
            for k in range(c2-1):
                temp=(q[i][k]*v[k][j])+(q[i][k+1]*v[k+1][j]) #MULTIPLICATION 
                p_mat.append(temp)
        p.append(p_mat)
    return(p)

r1=int(input('enter the number of rows for 1st matrix'))
c1=int(input('enter the number of columns for 1st matrix'))
r2=int(input('enter the number of rows for 2nd matrix'))
c2=int(input('enter the number of column for 2nd matrix'))

q=[]
v=[]
p=[]
for i in range(r1):
    t_mat=[]
    for j in range(c1):
        a=int(input('enter the value'))
        t_mat.append(a)
    q.append(t_mat)
    
for i in range(r2):
    t_mat=[]
    for j in range(c2):
        a=int(input('enter the value'))
        t_mat.append(a)
    v.append(t_mat)

print(q) 
print(v) 
if c1!=r2:
    print('not possilbe')   
else:
    print(mul(q,v))


    
#     return()
    
# matrix_mul(A, B)

enter the number of rows for 1st matrix2
enter the number of columns for 1st matrix2
enter the number of rows for 2nd matrix2
enter the number of column for 2nd matrix2
enter the value1
enter the value2
enter the value3
enter the value4
enter the value5
enter the value6
enter the value7
enter the value8
[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
[[19, 22], [43, 50]]


###### <h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


def pick_a_number_from_list(A,B): 
    for i in range(len(A)): #CUMULATIVE SUM
        B=B+A[i]
        cf_sum.append(B)
    num=int(random.uniform(0,B)) #PICKING RANDOM NUMBER
    for j in range(len(A)):
        if num>=cf_sum[j] and num<cf_sum[j+1]: #CHECKING THE INDEX WITH CUMULATIVE SUM
            return(A[j+1])
        else:
            continue

def sampling_based_on_magnitued():
    A = [0,5,27 ,6 ,13, 28, 100, 45, 10, 79]
    B=0
    cf_sum=[]
    for i in range(1,100):
        number = pick_a_number_from_list(A,B)
        print(number)

sampling_based_on_magnitued()

28
100
27
100
100
27
79
100
45


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
def replace_digits(String):
    pattern='[0-9]'
    st=re.findall(pattern,String)
    count=0
    for i in st:
        count+=1
    String="#"*count
    return(String) # string after replacing the # with digits
String=input("Enter the string")
replace_digits(String)


Enter the string23432erferf


'#####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
 Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

def display_dash_board_max(Students, Marks): #Who got top 5 ranks, in the descending order of marks
    #top_5_students
    new_marks=[]
    new_marks.extend(Marks)
    for i in range(5):
        m=max(new_marks)
        for a in range(len(Marks)): 
                if Marks[a]==m:
                    print(Students[a],m)
                    new_marks[a]=0
    return()
def display_dash_board_min(Students, Marks): #Who got least 5 ranks, in the increasing order of marks
#      least_5_students
    new_marks=[]
    new_marks.extend(Marks)
    for j in range(5):
        n=min(new_marks)
        for b in range(len(Marks)): 
            if Marks[b]==n:
                print(Students[b],n)
                new_marks[b]=100
    return()
def display_dash_board_percentile(Students,Marks): #Who got marks between >25th percentile <75th percentile, in the increasing order of marks
    new_marks=[]
    new_marks.extend(Marks)
    new_marks.sort()
    first=int(.25*len(Marks))
    Last=int(.75*len(Marks))
    for  i in range(first,Last):
        for j in range(len(Marks)):
            if (new_marks[i]==Marks[j]):
                print(Students[j],new_marks[i])
        
    return()

display_dash_board_max(Students, Marks)
print('\n')
display_dash_board_min(Students, Marks)
print('\n')
display_dash_board_percentile(Students,Marks)


student8 98
student10 80
student2 78
student5 48
student7 47


student3 12
student4 14
student9 35
student6 43
student1 45


student9 35
student6 43
student1 45
student7 47
student5 48


()

<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
import math

def closest_points_to_p(S, P):
    dist_list=[]
    for i in range(len(S)):
        x=S[i][0]
        y=S[i][1]
        p=P[0]
        q=P[1]
        
        num=x*p+y*q
        dino=(math.sqrt(x**2+y**2))*(math.sqrt((p**2+q**2))) #cosine distance
        dist=math.acos(num/dino)
        dist_list.append(dist)
    for j in range(5):
        q=min(dist_list)
        for k in range(len(dist_list)):
            if dist_list[k]==q: #checking if distance is equal to closest distance
                print(S[k])
                dist_list[k]=100
    return()

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)] #x,y
P= (3,-4)

closest_points_to_p(S, P)

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


()

<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
import re

def i_am_the_one(red,blue,line):
    eqn_1=[]
    eqn_2=[]
    e_1=[]
    e_2=[]
    o=[]
    for l in line: #getting the coefficient value of the equation and prepring a list
        for val in re.split('x|y',l):
            a=float(val.strip())
            eqn_1.append(a)
    new_eqn = [eqn_1[i:i+3] for i in range(0, len(eqn_1), 3)]
    for a in new_eqn:
        n1=[]
        n2=[]
        for i in red: 
            x1=i[0]
            y1=i[1]
            val_1= a[0] * float(x1) + a[1] * float(y1)+a[2] #calculating value replacing values of red nd coeff. of x,y 
            n1.append(val_1) 
        e_1.append(n1)
        for i in blue: 
            x2=i[0]
            y2=i[1]
            val_2= a[0] * float(x1) + a[1] * float(y1)+a[2] #calculating value replacing values of blue nd coeff. of x,y 
            n2.append(val_2) 
        e_2.append(n2)
    print(e_1)
    print(e_2)
    for i,j in zip(e_1,e_2):
        c=[]
        for l,m in zip(i,j): #calling both function together and calculatng the product
            q=l*m
            c.append(q)
        o.append(c)
    print(o)
    for index, row in enumerate(o):
        if all(col > 0 for col in row):  #checking is the product is less than or greater than 0
            print("YES")
        else:
            print("NO")
            
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

i_am_the_one(Red,Blue,Lines)





[[2.0, 3.0, 6.0, 6.0, 3.0], [0.0, 1.0, 2.0, -2.0, -5.0], [-2.0, -1.0, 1.0, -1.0, -4.0], [0.5, 0.5, 1.5, 3.5, 3.5]]
[[3.0, 3.0, 3.0, 3.0, 3.0], [-5.0, -5.0, -5.0, -5.0, -5.0], [-4.0, -4.0, -4.0, -4.0, -4.0], [3.5, 3.5, 3.5, 3.5, 3.5]]
[[6.0, 9.0, 18.0, 18.0, 9.0], [-0.0, -5.0, -10.0, 10.0, 25.0], [8.0, 4.0, -4.0, 4.0, 16.0], [1.75, 1.75, 5.25, 12.25, 12.25]]
YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:
import re 
s="_,_,30,_,_,_,50,_,_"
strn=s.split(',')
len_strn=len(strn)

def modify_string(strn):
  index=0
  for i in range(len_strn):
    if strn[i]=='_':
        index=index+1
    else:
      for j in range(i+1):
        strn[j]=str(float(strn[i])/(index+1))
        m_index=i
      m_number=float(strn[i])
      break
  count=0
  den=1
  for k in range(m_index+1,len_strn):
    if strn[k]!='_':
      den=k-m_index+1
      count=k
      break
  val=float(strn[count])
  for k in range(m_index,count+1):
    strn[k]=str((m_number+val)/den)
  last_val=float(strn[count])
  for l in range(count,len_strn):
    strn[l]=str((last_val)/(len_strn-count))

  return(strn)


  flag=0
modify_string(strn)

['10.0', '10.0', '12.0', '12.0', '12.0', '12.0', '4.0', '4.0', '4.0']

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/2, P(F=F1|S==S2)=1/2, P(F=F1|S==S3)=0/2
b. P(F=F2|S==S1)=1/3, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/3, P(F=F3|S==S2)=1/2, P(F=F3|S==S3)=1/2
d. P(F=F4|S==S1)=1/2, P(F=F4|S==S2)=0/2, P(F=F4|S==S3)=1/2
e. P(F=F5|S==S1)=1/1, P(F=F5|S==S2)=0/1, P(F=F5|S==S3)=0/1
</pre>



In [ ]:
def compute_conditional_probabilites(A):
    l=len(A) #answer = [all(n > 0 for n in lst) for lst in records]
    F=['F1','F2','F3','F4','F5']
    S=['S1','S2','S3']
    count_s1=0
    count_s2=0
    count_s3=0
    S1_f=[]
    S2_f=[]
    S3_f=[]
    dict_F1={}
    dict_F2={}
    dict_F3={}
    dict_F4={}
    dict_F5={}
    index=0
    for i in A: #calculating the count of all S1,S2 and S3
            if i[1]=='S1':
                count_s1+=1
            elif i[1]=='S2':
                count_s2+=1
            elif i[1]=='S3':
                count_s3+=1               
    for s in S: #calculating the count of all F1,F2... and theri possible combination with S1,S2..
        for i in range(len(A)):
            if A[i][0]=='F1'and A[i][1]==s:
                if 'F1%s'%s in dict_F1:
                    dict_F1['F1%s'%s]+=1
                else:
                    dict_F1['F1%s'%s]=1
            elif A[i][0]=='F2'and A[i][1]==s:
                if 'F2%s'%s in dict_F2:
                    dict_F2['F2%s'%s]+=1
                else:
                    dict_F2['F2%s'%s]=1
            elif A[i][0]=='F3'and A[i][1]==s:
                if 'F3%s'%s in dict_F3:
                    dict_F3['F3%s'%s]+=1
                else:
                    dict_F3['F3%s'%s]=1
            elif A[i][0]=='F4'and A[i][1]==s:
                if 'F4%s'%s in dict_F4:
                    dict_F4['F4%s'%s]+=1
                else:
                    dict_F4['F4%s'%s]=1
            elif A[i][0]=='F5'and A[i][1]==s:
                if 'F5%s'%s in dict_F5:
                    dict_F5['F5%s'%s]+=1
                else:
                    dict_F5['F5%s'%s]=1

    for f in F: #printing the probability ration of input F1,S1 to the total F1 and S1 present in the list
        if f=='F1':
            a=dict_F1.get('F1S1',0);b=dict_F1.get('F1S2',0);c=dict_F1.get('F1S3',0)
            print("P(F=F1|S==S1)=",a,"/",count_s1," ",'P(F=F1|S==S2)=',b,"/",count_s2," ",'P(F=F1|S==S3)=',c,"/",count_s3)
        if f=='F2':
            a=dict_F2.get('F2S1',0);b=dict_F2.get('F2S2',0);c=dict_F2.get('F2S3',0);            
            print('P(F=F2|S==S1)=',a,"/",count_s1," ",'P(F=F2|S==S2)=',b,"/",count_s2," ",'P(F=F2|S==S3)=',c,"/",count_s3)
        if f=='F3':
            a=dict_F3.get('F3S1',0);b=dict_F3.get('F3S2',0);c=dict_F3.get('F3S3',0);            
            print('P(F=F3|S==S1)=',a,"/",count_s1," ",'P(F=F3|S==S2)=',b,"/",count_s2," ",'P(F=F3|S==S3)=',c,"/",count_s3)
        if f=='F4':
            a=dict_F4.get('F4S1',0);b=dict_F4.get('F4S2',0);c=dict_F4.get('F4S3',0);
            print('P(F=F4|S==S1)=',a,"/",count_s1," ",'P(F=F4|S==S2)=',b,"/",count_s2," ",'P(F=F4|S==S3)=',c,"/",count_s3)
        if f=='F5':
            a=dict_F5.get('F5S1',0);b=dict_F5.get('F5S2',0);c=dict_F5.get('F5S3',0);
            print('P(F=F5|S==S1)=',a,"/",count_s1," ",'P(F=F5|S==S2)=',b,"/",count_s2," ",'P(F=F5|S==S3)=',c,"/",count_s3)
    
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F2','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F=F1|S==S1)= 1 / 4   P(F=F1|S==S2)= 0 / 3   P(F=F1|S==S3)= 0 / 3
P(F=F2|S==S1)= 1 / 4   P(F=F2|S==S2)= 2 / 3   P(F=F2|S==S3)= 1 / 3
P(F=F3|S==S1)= 0 / 4   P(F=F3|S==S2)= 1 / 3   P(F=F3|S==S3)= 1 / 3
P(F=F4|S==S1)= 1 / 4   P(F=F4|S==S2)= 0 / 3   P(F=F4|S==S3)= 1 / 3
P(F=F5|S==S1)= 1 / 4   P(F=F5|S==S2)= 0 / 3   P(F=F5|S==S3)= 0 / 3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
import re
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a=re.split(" ",S1)
b=re.split(" ",S2)
len1=len(a)
len2=len(b)
commons1=[]
commons2=[]
def commonword(S1,S2):#finding  common words
    count=0
    for i in range(len1): #Number of common words between S1, S2
        for j in range(len2):
            if b[j]==a[i]:
                count+=1
    print('a.',count,'\n')
    for i1 in range(len1):
        flag=0
        for j1 in range(len2): #Words in S1 but not in S2
            if a[i1]==b[j1]:
                flag=1
                break
        if flag==0:
            commons1.append(a[i1])
    print('b.',commons1,'\n')
    
    for i1 in range(len1):
        flag=0
        for j1 in range(len2): #Words in S2 but not in S1
            if b[i1]==a[j1]:
                flag=1
                break
        if flag==0:
            commons2.append(b[i1])
    print('c.',commons2)
    
commonword(S1,S2)


a. 7 

b. ['first', 'F', '5'] 

c. ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
import math
def compute_log_loss(A):
    n=len(A)
    loss=0
    for i in range(n): #calculating the value of the equation 
        calc=int(A[i][0])*math.log10((A[i][1]))+int(1-A[i][0])*math.log10(1-(A[i][1]))       
        loss=loss+calc
    loss=-(loss/n)
    return(loss)

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
